config/routes.rb
Rails.application.routes.draw do

  # You can have the root of your site routed with "root"
  root :to => 'home#index'

  resources :rewards, only: [:new, :show, :update] do
    collection do
      post :webhook
    end

    member do
      post :error
    end
  end
end

app/models/Webhook.rb
module Webhook
  def self.handle(body)
    Rails.logger.info("GiftRocket webhook fired :: #{body}")
    # Each webhook contains a event_id property.
    # Retries due to failed responses by this server will
    # contain the same event_id. We could store this value
    # and discard duplicate webhooks or we can make our code idempotent.

    case body[:event]
    when "gift.REDEEMED"
      self.on_redeemed(body[:payload])
    when "gift.PAYOUT_CANCELED"
      self.on_payout_canceled(body[:payload])
    when "gift.PAYOUT_FAILED"
      self.on_payout_failed(body[:payload])
    when "funding.NFS"
      # Our GiftRocket account balance is insufficient.
      # We must execute a wire or ACH payment to add more funds.
      # This should notify an administrator internally.

    end
  end

  def self.on_redeemed(reward)
    reward = Reward.find_by_giftrocket_id(reward[:id])
    # We can confirm that the state of our reward is correct (:redeemed)
    # gift = Giftrocket::Gift.retrieve(payload[:id])
    # payout = gift.raw[:payouts].first
  end

  def self.on_payout_canceled(reward)
    # The user or your team initiated a cancellation of the payout
    # typically so that the recipient can select a different option.
    # Cancel the payout and communicate to the user to redeem again.
    RewardPayout.find_by_giftrocket_id(
      reward[:payout][:id]
    ).cancel!
  end

  def self.on_payout_failed(reward)
    # The recipient provided bad redemption information or the payout
    # otherwise failed. Fail the payout and communicate to the user to redeem again.
    RewardPayout.find_by_giftrocket_id(
      reward[:payout][:id]
    ).fail!
  end
end

app/models/catalog_product.rb
class CatalogProduct < ActiveRecord::Base
  has_many :skus, class_name: "CatalogProductSku", :dependent => :destroy
end

app/models/catalog_product_sku.rb
class CatalogProductSku < ActiveRecord::Base
  has_many :rewards
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  enum status: [:redeemable, :redeemed]

  belongs_to :user
  belongs_to :catalog_product
  has_many :reward_payouts

  before_create :set_defaults
  before_create :generate_public_token

  def reset_to_redeemable!
    redeemable!
    # Communicate to the user that they should attempt to
    # redeem their reward again.
  end

  def payout
    reward_payouts.order("created_at DESC").first
  end

  protected
    def set_defaults
      self.status = Reward.statuses[:redeemable]
    end

    def generate_public_token
      self.public_token = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless Reward.exists?(public_token: random_token)
      end
    end
end

app/models/reward_payout.rb
class RewardPayout < ActiveRecord::Base
  serialize :data, Hash
  # We can map status to the enum below.  For more future flexibility,
  # we can also just leave it as string as we have in this sample app.
  # enum status: [:unexecuted, :executing, :completed, :failed, :canceled]

  belongs_to :reward
  belongs_to :catalog_product

  def cancel!
    update_attributes({status: "CANCELED"})
    reward.reset_to_redeemable!
  end

  def fail!
    update_attributes({status: "FAILED"})
    reward.reset_to_redeemable!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rewards = Reward.redeemed
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def new
    @reward = create_new_reward!

    # Either specifically set the catalog for
    # your recipients or enable all payout options for that currency.
    @catalog = CatalogProduct.all.select do |item|
      ["MERCHANT_CARDS", "VISA"].include?(item.category)
    end.map(&:giftrocket_id)

    # The public key is passed to the Reward js initializer.
    # It is used in conjunction with the private key to decode the JWT.
    @public_key = GIFTROCKET_EMBED_PUBLIC_KEY

    # The reward data (amount, currency, external_id, etc.) is encrypted
    # with GiftRocket API private key and only readable using that same key.
    @token = tokenize_reward_configuration(@reward)
  end

  def show
    @reward = Reward.find_by_id(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless @reward.present?

    @public_key = GIFTROCKET_EMBED_PUBLIC_KEY
    @token = tokenize_reward_configuration(@reward)
  end

  def update
    # After the reward is created via the javascript SDK,
    # we hit this endpoint with the ID from our system
    # to eventually retrieve the full reward data from the GiftRocket REST API.
    reward = Reward.find_by_id(params[:id])
    if reward.blank?
      logger.error("Attempt to re-redeem reward :: #{params[:id]}")
      render status: 401, json: {}
    elsif reward.redeemed?
      logger.warn("Attempt to re-redeem reward :: #{params[:id]}")
      render json: {}
    else
      logger.info("Redeem reward :: #{params[:id]}")
      reward.update_attributes({
        giftrocket_id: params[:giftrocket_id],
        status: Reward.statuses[:redeemed]
      })

      begin
        gift = Giftrocket::Gift.retrieve(reward.giftrocket_id)
        # Payouts returned in descending chronological order
        payout = gift.raw[:payouts].first

        RewardPayout.create!({
          reward: reward,
          created_at: DateTime.strptime("#{payout[:created_at]}",'%s'),
          giftrocket_id: payout[:id],
          status: payout[:status],
          catalog_product_id: CatalogProduct.find_by_giftrocket_id(payout[:catalog_id]).id,
          data: payout[:data]
        })

        render json: {}
      rescue => e
        logger.error("Redeem reward failed :: #{params[:id]}")
        logger.error e.message
        logger.error e.backtrace.join("\n")

        render status: 500, json: {}
      end
    end
  end

  def error
  end

  def webhook
    # This should be handled in an asynchronous worker if possible
    # so that we can respond to the webhook quickly.
    Webhook.handle(params)
    render status: 200, json: {}
  end

  private
    def create_new_reward!
      # For demo purposes, we create a new reward each time we render the page.
      # This is more convenient than running a rake task to generate new model instances.
      user = User.find_or_create_by({
        name: 'Test User',
        email: "test@mydomain.com"
      })

      Reward.create!({
        user: user,
        amount: (params[:amount].presence || 50).to_i
      })
    end

    def require_reward
      reward = Reward.find_by_id(params[:id])
      if reward.blank?
        logger.error("Attempt to re-redeem completed reward #{params[:id]}")
        render status: 404, json: {}
      end
    end

    def tokenize_reward_configuration(reward)
      Giftrocket::Embed.tokenize({
        amount: reward.amount,
        currency_code: "USD",
        external_id: reward.public_token,
        recipient: {
          email: reward.user.email,
          name: reward.user.name
        },
      })
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
  <div style="line-height: 1.5">
    <a class="btn btn-primary" href="/rewards/new">Create a new reward</a>
  </div>

  <div style="margin-top: 20px">
    <table class="table">
      <caption>Rewards History</caption>
      <thead>
        <tr>
          <th>ID</th>
          <th></th>
          <th>Amount ($USD)</th>
          <th>Recipient Name</th>
          <th>Recipient Email</th>
          <th>Status</th>
          <th>Payout</th>
        </tr>
      </thead>
      <tbody>
        <% @rewards.map do |reward| %>
          <tr>
            <td><%= reward.id %></td>
            <td>
              <a href="<%= reward_path(id: reward.id) %>">view</a>
            </td>
            <td><%= reward.amount %></td>
            <td><%= reward.user.name %></td>
            <td><%= reward.user.email %></td>
            <td><%= reward.status.upcase %></td>
            <td><%= reward.payout.try(:catalog_product).try(:name) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>GiftRocket Embed Demo Application</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta content='noindex, follow' name='robots'>

  <%= stylesheet_link_tag "application" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>
</head>
  <body>
    <div class="container">
      <div class="brand">
        <a href="/">Rails Embed Demo</a>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/rewards/new.html.erb
<div class="center" style="margin-top: 60px">
  <h2>
    thank you!
  </h2>

  <p style="line-height: 1.5">
    Your funds are ready. <br /> This is a demo of GiftRocket Embed.
  </p>

  <div style="margin-top: 20px">
    <button style="margin-bottom: 20px;" class="btn btn-primary" id="launchpad">
      Claim $50
    </button>

    <div class="label--launch"><i>Launches the embedded module</i></div>
  </div>
</div>

<%= javascript_include_tag "https://cdn.giftrocket.com/embed/v1.2.0/client.js" %>

<script type="text/javascript">

  var reward = Reward("<%= @public_key %>", Reward.env.SANDBOX);

  function redeem() {
    var request = function (method, url, data, cbk) {
      return $.ajax({
        method: method,
        url: url,
        data: data
      }).done(cbk);
    };

    reward.redeem(
      "<%= @token.html_safe %>",
      {
        config: {
          // catalog: <%= @catalog.to_json.html_safe %>
        },
        onLoad: function(config) {
          console.log("It loaded!");
        },
        onExit: function() {
          console.log("Please come back");
        },
        onError: function(err) {
          // request("POST", "/rewards/error", err);
        },
        onSuccess: function(result) {
          request("PUT", "/rewards/<%= @reward.id %>", {giftrocket_id: result.id}, function(response) {
              // In a real app, we would validate the response.
              // window.location = "/";
            }
          );
        }
      }
    );
  }

  $("#launchpad").on("click", redeem);

</script>

app/views/rewards/show.html.erb
<div class="center">
  <div>
    You've already redeemed this reward.
  </div>

  <div style="margin-top: 20px">
    <button style="margin-bottom: 20px;" class="btn btn-primary" id="launchpad">
      View Details
    </button>

    <div class="label--launch"><i>Launches the embedded module</i></div>
  </div>
</div>

<%= javascript_include_tag "https://cdn.giftrocket.com/embed/v1.2.0/client.js" %>

<script type="text/javascript">

var reward = Reward("<%= @public_key %>", Reward.env.SANDBOX);

function redeem() {

  var request = function (method, url, data, cbk) {
    return $.ajax({
      method: method,
      url: url,
      data: data
    }).done(cbk);
  };

  reward.redeem(
    "<%= @token.html_safe %>",
    {
      onLoad: function(config) {
        console.log("It loaded!");
      },
      onExit: function() {
        console.log("Please come back");
      },
      onError: function(err) {
        // request("POST", "/rewards/error", err);
      },
    }
  );
}

$("#launchpad").on("click", redeem);

</script>